export const ROUTES = [
  { path: '/', name: 'Introduction' },
  // { path: '/chapters/meshes', name: 'Meshes' },
  // { path: '/chapters/meshes/result', name: 'Meshes' },
  // { path: '/chapters/geometry', name: 'Geometry' },
  // { path: '/chapters/material', name: 'Material' },
  // { path: '/chapters/worlds', name: 'Worlds' },
  // { path: '/chapters/lights', name: 'Lights' },
  { path: '/chapters/computer-graphics', name: 'computer-graphics' },
  { path: '/chapters/open-gl', name: 'open-gl' },
  { path: '/chapters/web-gl', name: 'web-gl' },
  { path: '/chapters/three', name: 'three' },
  { path: '/chapters/r3f', name: 'r3f' },
  { path: '/chapters/installation', name: 'installation' },
  { path: '/chapters/usage', name: 'usage' },
  { path: '/chapters/mesh-decomposition', name: 'mesh-decomposition' },
  { path: '/chapters/geometry', name: 'geometry' },
  { path: '/chapters/materials', name: 'materials' },
  { path: '/chapters/mesh', name: 'mesh' },
  { path: '/chapters/lights', name: 'lights' },
  { path: '/chapters/cameras', name: 'cameras' },
  { path: '/chapters/animations', name: 'animations' },
  { path: '/chapters/physics', name: 'physics' },
  { path: '/chapters/worlds', name: 'worlds' },
  { path: '/chapters/performance-animations', name: 'performance-animations' },
  { path: '/chapters/performance-instantiation', name: 'performance-instantiation' },
  { path: '/chapters/resources', name: 'resources' },
  { path: '/chapters/people', name: 'people' },
  { path: '/chapters/effects', name: 'effects' },
]
