export const ROUTES = [
  { path: '/', name: 'Introduction' },
  // { path: '/chapters/meshes', name: 'Meshes' },
  // { path: '/chapters/meshes/result', name: 'Meshes' },
  // { path: '/chapters/geometry', name: 'Geometry' },
  // { path: '/chapters/material', name: 'Material' },
  // { path: '/chapters/worlds', name: 'Worlds' },
  // { path: '/chapters/lights', name: 'Lights' },
  { path: '/chapters/computer-graphics', name: 'Computer Graphics' },
  // { path: '/chapters/open-gl', name: 'OpenGL' },
  { path: '/chapters/web-gl', name: 'WebGL' },
  { path: '/chapters/three', name: 'Three.js' },
  { path: '/chapters/r3f', name: '@react-three/fiber' },
  { path: '/chapters/installation', name: 'Installation' },
  { path: '/chapters/usage', name: 'Usage' },
  { path: '/chapters/mesh', name: 'Mesh' },
  { path: '/chapters/geometry', name: 'Geometry' },
  { path: '/chapters/materials', name: 'Materials' },
  { path: '/chapters/lights', name: 'Lights' },
  { path: '/chapters/cameras', name: 'Cameras' },
  { path: '/chapters/animations', name: 'Animations' },
  { path: '/chapters/physics', name: 'Physics' },
  // { path: '/chapters/worlds', name: 'Worlds' },
  { path: '/chapters/performance-animations', name: 'Performance - Animations' },
  { path: '/chapters/performance-instantiation', name: 'Performance - Instantiation' },
  { path: '/chapters/resources', name: 'Resources' },
  { path: '/chapters/people', name: 'People' },
  { path: '/chapters/effects', name: 'Effects' },
]
